name: ECS Infrastructure

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  update_infrastructure:
    name: Update ECS infrastructure
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
